DEGREE_SIGN= u'\N{DEGREE SIGN}'
HUMIDITY = 'Humidity: %d%%'

TEMPERATURE_TEXT_SIZE=140
DEGREE_UNIT_TEXT_SIZE=60
WEATHER_DETAILS_TEXT_SIZE=38

WEATHER_REFRESH_RATE=600000 # 10 Minutes
WEATHER_REQUEST_ENDPOINT="https://api.darksky.net/forecast/%s/%s,%s?lang=%s&units=%s"

KELVIN="K"
CELCIUS="C"
FAHRENHEIT="F"
